CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    real_name VARCHAR(50),
    student_no VARCHAR(30),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
